from __future__ import annotations

import base64
import csv
import hashlib
import io
import json
import os
import socket
from pathlib import Path
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

import pytest

from provelume.installation_verification import (
    verify_installed_distribution,
    verify_record_installation,
)

VERSION = "0.1.0"
COMMIT = "5" * 40


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _record_hash(data: bytes) -> str:
    encoded = base64.urlsafe_b64encode(hashlib.sha256(data).digest()).rstrip(b"=")
    return "sha256=" + encoded.decode("ascii")


def _record_text(rows: list[tuple[str, bytes | None]]) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    for name, data in rows:
        if data is None:
            writer.writerow([name, "", ""])
        else:
            writer.writerow([name, _record_hash(data), str(len(data))])
    return output.getvalue()


def _installation(tmp_path: Path, *, metadata_name: str = "provelume") -> dict[str, Path]:
    root = tmp_path / "site-packages"
    package = root / "provelume"
    dist_info = root / f"provelume-{VERSION}.dist-info"
    bytecode = package / "__pycache__"
    package.mkdir(parents=True)
    dist_info.mkdir()
    bytecode.mkdir()

    init = package / "__init__.py"
    service = package / "service.py"
    metadata = dist_info / "METADATA"
    record = dist_info / "RECORD"
    pyc = bytecode / "service.cpython-312.pyc"

    init.write_bytes(b'__version__ = "0.1.0"\n')
    service.write_bytes(b"def identity():\n    return 'public-core'\n")
    metadata.write_text(
        f"Metadata-Version: 2.3\nName: {metadata_name}\nVersion: {VERSION}\n",
        encoding="utf-8",
    )
    pyc.write_bytes(b"generated bytecode")

    rows = [
        ("provelume/__init__.py", init.read_bytes()),
        ("provelume/service.py", service.read_bytes()),
        (
            f"provelume-{VERSION}.dist-info/METADATA",
            metadata.read_bytes(),
        ),
        ("provelume/__pycache__/service.cpython-312.pyc", None),
        ("../../../bin/provelume", None),
        (f"provelume-{VERSION}.dist-info/RECORD", None),
    ]
    record.write_text(_record_text(rows), encoding="utf-8")
    return {
        "root": root,
        "package": package,
        "init": init,
        "service": service,
        "metadata": metadata,
        "record": record,
        "pyc": pyc,
    }


def _identity(path: Path) -> dict[str, Any]:
    return {
        "filename": path.name,
        "size_bytes": path.stat().st_size,
        "sha256": _digest(path.read_bytes()),
    }


def _write_json(path: Path, value: dict[str, Any]) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _wheel_bytes(files: dict[str, Path], *, unsafe_member: str | None = None) -> bytes:
    members: dict[str, bytes] = {
        "provelume/__init__.py": files["init"].read_bytes(),
        "provelume/service.py": files["service"].read_bytes(),
        f"provelume-{VERSION}.dist-info/METADATA": files["metadata"].read_bytes(),
        f"provelume-{VERSION}.dist-info/WHEEL": (
            b"Wheel-Version: 1.0\nGenerator: synthetic-public-test\n"
            b"Root-Is-Purelib: true\nTag: py3-none-any\n"
        ),
    }
    if unsafe_member is not None:
        members[unsafe_member] = b"unsafe synthetic member"
    rows = [(name, data) for name, data in members.items()]
    record_name = f"provelume-{VERSION}.dist-info/RECORD"
    record = _record_text([*rows, (record_name, None)]).encode("utf-8")
    members[record_name] = record

    buffer = io.BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        for name, data in members.items():
            archive.writestr(name, data)
    return buffer.getvalue()


def _release_bundle(
    tmp_path: Path,
    files: dict[str, Path],
    *,
    unsafe_wheel_member: str | None = None,
) -> Path:
    root = tmp_path / "release"
    root.mkdir()
    wheel = root / f"provelume-{VERSION}-py3-none-any.whl"
    sdist = root / f"provelume-{VERSION}.tar.gz"
    license_file = root / "LICENSE"
    sbom = root / f"provelume-{VERSION}.cdx.json"

    wheel.write_bytes(_wheel_bytes(files, unsafe_member=unsafe_wheel_member))
    sdist.write_bytes(b"synthetic public source distribution")
    license_file.write_text("Synthetic license\n", encoding="utf-8")
    _write_json(
        sbom,
        {
            "bomFormat": "CycloneDX",
            "specVersion": "1.6",
            "version": 1,
            "components": [],
        },
    )
    artifacts = [wheel, sdist, license_file]
    manifest = {
        "schema_version": 1,
        "version": VERSION,
        "tag": f"v{VERSION}",
        "commit": COMMIT,
        "source_repository": "gabned/provelume",
        "channel": "preview",
        "build_timestamp": "2026-08-23T17:00:00Z",
        "assurance_level": "traceable-build",
        "artifacts": [_identity(path) for path in artifacts],
        "sbom": {**_identity(sbom), "format": "CycloneDX 1.6"},
    }
    _write_json(root / "release-manifest.json", manifest)
    checksummed = [*artifacts, sbom]
    (root / "SHA256SUMS").write_text(
        "".join(f"{_digest(path.read_bytes())}  {path.name}\n" for path in checksummed),
        encoding="utf-8",
    )
    return root


def _rewrite_record(files: dict[str, Path], extra_rows: list[tuple[str, bytes | None]] = []) -> None:
    rows = [
        ("provelume/__init__.py", files["init"].read_bytes()),
        ("provelume/service.py", files["service"].read_bytes()),
        (
            f"provelume-{VERSION}.dist-info/METADATA",
            files["metadata"].read_bytes(),
        ),
        *extra_rows,
        ("provelume/__pycache__/service.cpython-312.pyc", None),
        ("../../../bin/provelume", None),
        (f"provelume-{VERSION}.dist-info/RECORD", None),
    ]
    files["record"].write_text(_record_text(rows), encoding="utf-8")


def test_local_record_verification_is_offline_and_explains_trust_boundary(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    files = _installation(tmp_path)

    def deny_network(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("installation verifier attempted network access")

    monkeypatch.setattr(socket, "create_connection", deny_network)
    result = verify_record_installation(files["root"], files["record"])

    assert result.status == "verified"
    assert result.version == VERSION
    assert result.checked_files == 3
    assert result.core_files == 2
    assert result.ignored_generated_files == 1
    assert result.out_of_scope_entries == 1
    assert result.release_wheel_status == "not_checked"
    assert any(finding.code == "trust.local_record_only" for finding in result.findings)


def test_modified_or_missing_core_file_fails_closed(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    files["service"].write_bytes(b"locally modified core")
    modified = verify_record_installation(files["root"], files["record"])
    assert modified.status == "modified"
    assert any(finding.code == "record.identity" for finding in modified.findings)

    files = _installation(tmp_path / "missing")
    files["service"].unlink()
    missing = verify_record_installation(files["root"], files["record"])
    assert missing.status == "modified"


def test_unrecorded_core_file_and_symlink_are_visible(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    (files["package"] / "unexpected.py").write_text("unexpected = True\n", encoding="utf-8")
    unexpected = verify_record_installation(files["root"], files["record"])
    assert unexpected.status == "modified"
    assert any(finding.code == "core.unrecorded" for finding in unexpected.findings)

    if not hasattr(os, "symlink"):
        return
    files = _installation(tmp_path / "symlink")
    outside = tmp_path / "outside.py"
    outside.write_bytes(files["service"].read_bytes())
    files["service"].unlink()
    try:
        os.symlink(outside, files["service"])
    except OSError:
        return
    linked = verify_record_installation(files["root"], files["record"])
    assert linked.status == "modified"
    assert outside.read_bytes() == b"def identity():\n    return 'public-core'\n"


def test_record_rejects_alias_traversal_and_windows_drive_prefix(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    _rewrite_record(
        files,
        [("provelume/../provelume/alias.py", b"alias")],
    )
    traversal = verify_record_installation(files["root"], files["record"])
    assert traversal.status == "modified"

    files = _installation(tmp_path / "drive")
    _rewrite_record(files, [("C:outside.py", b"outside")])
    drive = verify_record_installation(files["root"], files["record"])
    assert drive.status == "modified"


def test_unhashed_core_identity_is_unavailable(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    rows = [
        ("provelume/__init__.py", None),
        ("provelume/service.py", files["service"].read_bytes()),
        (
            f"provelume-{VERSION}.dist-info/METADATA",
            files["metadata"].read_bytes(),
        ),
        (f"provelume-{VERSION}.dist-info/RECORD", None),
    ]
    files["record"].write_text(_record_text(rows), encoding="utf-8")

    result = verify_record_installation(files["root"], files["record"])

    assert result.status == "unavailable"


def test_metadata_name_and_expected_version_are_enforced(tmp_path: Path) -> None:
    files = _installation(tmp_path, metadata_name="another-project")
    wrong_name = verify_record_installation(files["root"], files["record"])
    assert wrong_name.status == "modified"

    files = _installation(tmp_path / "version")
    wrong_version = verify_record_installation(
        files["root"],
        files["record"],
        expected_version="9.9.9",
    )
    assert wrong_version.status == "modified"


def test_verified_release_wheel_strengthens_installed_byte_identity(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    release = _release_bundle(tmp_path, files)

    result = verify_record_installation(
        files["root"],
        files["record"],
        release_bundle=release,
    )

    assert result.status == "verified"
    assert result.release_wheel_status == "verified"
    assert result.release_version == VERSION
    assert result.release_commit == COMMIT
    assert result.matched_release_wheel == f"provelume-{VERSION}-py3-none-any.whl"
    assert any(finding.code == "installation.release_match" for finding in result.findings)


def test_modified_record_cannot_hide_divergence_from_release_wheel(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    release = _release_bundle(tmp_path, files)
    files["service"].write_bytes(b"modified and re-recorded")
    _rewrite_record(files)

    local_only = verify_record_installation(files["root"], files["record"])
    assert local_only.status == "verified"

    linked = verify_record_installation(
        files["root"],
        files["record"],
        release_bundle=release,
    )
    assert linked.status == "modified"
    assert linked.release_wheel_status == "modified"
    assert any(finding.code == "release_wheel.invalid" for finding in linked.findings)


def test_unsafe_release_wheel_member_fails_closed(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    release = _release_bundle(tmp_path, files, unsafe_wheel_member="../escape.py")

    result = verify_record_installation(
        files["root"],
        files["record"],
        release_bundle=release,
    )

    assert result.status == "modified"
    assert result.release_wheel_status == "modified"
    assert not (tmp_path / "escape.py").exists()


def test_invalid_release_bundle_cannot_be_used_as_trust_input(tmp_path: Path) -> None:
    files = _installation(tmp_path)
    release = _release_bundle(tmp_path, files)
    (release / "SHA256SUMS").write_text("invalid\n", encoding="utf-8")

    result = verify_record_installation(
        files["root"],
        files["record"],
        release_bundle=release,
    )

    assert result.status == "modified"
    assert result.release_wheel_status == "modified"


def test_missing_distribution_is_unavailable() -> None:
    result = verify_installed_distribution("definitely-not-installed-provelume-test")
    assert result.status == "unavailable"
    assert any(finding.code == "distribution.not_found" for finding in result.findings)
