"""Derive Core/Windows brand assets from the canonical, bounded public SVG.

The renderer supports only this mark's explicit SVG subset. Unsupported syntax
fails closed. Cubics use 32 segments and rasterization uses a fixed 4x grid.
PNG uses stored DEFLATE blocks so zlib versions cannot change generated bytes.
"""

import argparse
import hashlib
import json
import math
import re
import struct
import xml.etree.ElementTree as ET
import zlib
from pathlib import Path

SIZES = (16, 20, 24, 32, 40, 48, 64, 128, 256)
SUPERSAMPLE = 4
ROOT = Path(__file__).resolve().parents[1]
SOURCE = "assets/windows/provelume.svg"


def validate_source(source):
    if len(source) > 32768 or b"<!" in source:
        raise ValueError("Bounded SVG without declarations required")
    root = ET.fromstring(source)
    namespace = "{http://www.w3.org/2000/svg}"
    if root.tag != namespace + "svg" or root.attrib.get("viewBox") != "0 0 64 64":
        raise ValueError("Canonical 64x64 SVG required")
    if set(root.attrib) - {"viewBox", "role", "aria-labelledby"} or len(root) > 16:
        raise ValueError("Unsupported SVG root")
    allowed = {
        "title": {"id"},
        "desc": {"id"},
        "rect": {"x", "y", "width", "height", "rx", "fill"},
        "circle": {"cx", "cy", "r", "fill"},
        "path": {"d", "fill", "stroke", "stroke-width", "stroke-linecap", "stroke-linejoin"},
    }
    for element in root:
        tag = element.tag.removeprefix(namespace)
        if (
            element.tag != namespace + tag
            or tag not in allowed
            or set(element.attrib) - allowed[tag]
            or len(element)
        ):
            raise ValueError("Unsupported SVG element or attribute")
        a = element.attrib
        for key, value in a.items():
            if key in {"fill", "stroke"} and not (
                value == "none" or re.fullmatch(r"#[0-9a-fA-F]{6}", value)
            ):
                raise ValueError("Only solid RGB fills and strokes are supported")
            if key in {"stroke-linecap", "stroke-linejoin"} and value != "round":
                raise ValueError("Only round strokes are supported")
            if key in {"x", "y", "width", "height", "rx", "cx", "cy", "r", "stroke-width"} and (
                not re.fullmatch(r"\d+(?:\.\d+)?", value) or not 0 <= float(value) <= 64
            ):
                raise ValueError("SVG coordinate exceeds the supported bounds")
        if tag == "path":
            if "stroke" in a and (a.get("stroke-linecap") != "round" or "stroke-width" not in a):
                raise ValueError("Explicit round stroke required")
            if a.get("fill", "none") != "none" and not a.get("d", "").endswith("Z"):
                raise ValueError("Explicit closed fill required")
        if tag == "rect" and (
            float(a.get("rx", 0)) * 2 > min(float(a["width"]), float(a["height"]))
        ):
            raise ValueError("Unsupported rounded rectangle")
    return root


def path_points(data):
    tokens = re.findall(r"[MLHVCZ]|-?(?:\d+\.?\d*|\.\d+)", data)
    if re.sub(r"[\s,MLHVCZ0-9.\-]", "", data):
        raise ValueError("Unsupported SVG path")
    if not tokens or tokens[0] != "M" or tokens.count("M") != 1 or len(tokens) > 512:
        raise ValueError("One bounded path with explicit move required")
    points = []
    i = 0
    x = y = 0.0
    while i < len(tokens):
        command = tokens[i]
        i += 1
        count = {"M": 2, "L": 2, "H": 1, "V": 1, "C": 6, "Z": 0}.get(command)
        if count is None:
            raise ValueError("Explicit SVG commands required")
        values = [float(t) for t in tokens[i : i + count]]
        i += count
        if len(values) != count:
            raise ValueError("Truncated SVG path")
        if not all(math.isfinite(v) and 0 <= v <= 64 for v in values):
            raise ValueError("Path outside bounds")
        if command == "Z" and i != len(tokens):
            raise ValueError("Close must end the path")
        if command in {"M", "L"}:
            x, y = values
            points.append((x, y))
        elif command == "H":
            x = values[0]
            points.append((x, y))
        elif command == "V":
            y = values[0]
            points.append((x, y))
        elif command == "C":
            ax, ay, bx, by, cx, cy = values
            for step in range(1, 33):
                t = step / 32
                u = 1 - t
                points.append(
                    (
                        u**3 * x + 3 * u * u * t * ax + 3 * u * t * t * bx + t**3 * cx,
                        u**3 * y + 3 * u * u * t * ay + 3 * u * t * t * by + t**3 * cy,
                    )
                )
            x, y = cx, cy
        elif command == "Z":
            points.append(points[0])
    return points


def scene(source):
    root = validate_source(source)
    if root.attrib.get("viewBox") != "0 0 64 64":
        raise ValueError("Unsupported view box")
    shapes = []
    for e in root:
        tag = e.tag.rsplit("}", 1)[-1]
        a = e.attrib
        if tag in {"title", "desc"}:
            continue
        fill = a.get("fill", "#000000")
        stroke = a.get("stroke")
        if tag == "rect":
            x = float(a.get("x", 0))
            y = float(a.get("y", 0))
            w = float(a["width"])
            h = float(a["height"])
            radius = float(a.get("rx", 0))
            shapes.append(
                (
                    "polygon",
                    [
                        (x + radius, y),
                        (x + w - radius, y),
                        (x + w - radius, y + h),
                        (x + radius, y + h),
                    ],
                    fill,
                )
            )
            shapes.append(
                (
                    "polygon",
                    [
                        (x, y + radius),
                        (x + w, y + radius),
                        (x + w, y + h - radius),
                        (x, y + h - radius),
                    ],
                    fill,
                )
            )
            for cx, cy in [
                (x + radius, y + radius),
                (x + w - radius, y + radius),
                (x + radius, y + h - radius),
                (x + w - radius, y + h - radius),
            ]:
                shapes.append(("circle", (cx, cy, radius), fill))
        elif tag == "circle":
            shapes.append(("circle", (float(a["cx"]), float(a["cy"]), float(a["r"])), fill))
        elif tag == "path":
            points = path_points(a["d"])
            if fill != "none":
                shapes.append(("polygon", points, fill))
            if stroke:
                radius = float(a["stroke-width"]) / 2
                for (ax, ay), (bx, by) in zip(points, points[1:], strict=False):
                    length = math.hypot(bx - ax, by - ay)
                    if not length:
                        continue
                    nx = -(by - ay) / length * radius
                    ny = (bx - ax) / length * radius
                    shapes.append(
                        (
                            "polygon",
                            [
                                (ax + nx, ay + ny),
                                (bx + nx, by + ny),
                                (bx - nx, by - ny),
                                (ax - nx, ay - ny),
                            ],
                            stroke,
                        )
                    )
                for x, y in points:
                    shapes.append(("circle", (x, y, radius), stroke))
        else:
            raise ValueError("Unsupported SVG element")
    return shapes


def rgba(size, shapes):
    width = size * SUPERSAMPLE
    scale = width / 64
    pixels = bytearray(width * width * 4)
    for kind, geometry, color in shapes:
        if not re.fullmatch(r"#[0-9A-Fa-f]{6}", color):
            raise ValueError("Solid RGB required")
        ink = bytes.fromhex(color[1:]) + b"\xff"
        if kind == "circle":
            cx, cy, radius = [v * scale for v in geometry]
            ymin = cy - radius
            ymax = cy + radius
        else:
            points = [(x * scale, y * scale) for x, y in geometry]
            ymin = min(y for x, y in points)
            ymax = max(y for x, y in points)
        for row in range(max(0, math.ceil(ymin - 0.5)), min(width, math.ceil(ymax - 0.5))):
            y = row + 0.5
            if kind == "circle":
                reach = math.sqrt(max(0, radius * radius - (y - cy) ** 2))
                spans = [(cx - reach, cx + reach)]
            else:
                cuts = []
                for (ax, ay), (bx, by) in zip(points, points[1:] + points[:1], strict=True):
                    if (ay <= y < by) or (by <= y < ay):
                        cuts.append(ax + (y - ay) * (bx - ax) / (by - ay))
                cuts.sort()
                spans = list(zip(cuts[::2], cuts[1::2], strict=True))
            for left, right in spans:
                start = max(0, math.ceil(left - 0.5))
                end = min(width, math.ceil(right - 0.5))
                if end > start:
                    pixels[(row * width + start) * 4 : (row * width + end) * 4] = ink * (
                        end - start
                    )
    result = bytearray(size * size * 4)
    for y in range(size):
        for x in range(size):
            red = green = blue = alpha = 0
            for sy in range(SUPERSAMPLE):
                offset = ((y * SUPERSAMPLE + sy) * width + x * SUPERSAMPLE) * 4
                for sx in range(SUPERSAMPLE):
                    i = offset + sx * 4
                    a = pixels[i + 3]
                    red += pixels[i] * a
                    green += pixels[i + 1] * a
                    blue += pixels[i + 2] * a
                    alpha += a
            value = (
                bytes(
                    (
                        round(red / alpha),
                        round(green / alpha),
                        round(blue / alpha),
                        round(alpha / SUPERSAMPLE**2),
                    )
                )
                if alpha
                else b"\0\0\0\0"
            )
            result[(y * size + x) * 4 : (y * size + x + 1) * 4] = value
    return bytes(result)


def chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))


def png(size, shapes):
    data = rgba(size, shapes)
    rows = b"".join(b"\0" + data[i : i + size * 4] for i in range(0, len(data), size * 4))
    blocks = [rows[i : i + 65535] for i in range(0, len(rows), 65535)]
    compressed = (
        b"\x78\x01"
        + b"".join(
            bytes([int(i == len(blocks) - 1)])
            + struct.pack("<HH", len(block), 65535 - len(block))
            + block
            for i, block in enumerate(blocks)
        )
        + struct.pack(">I", zlib.adler32(rows))
    )
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", compressed)
        + chunk(b"IEND", b"")
    )


def ico(images):
    offset = 6 + 16 * len(images)
    entries = bytearray()
    payload = bytearray()
    for size, image in images:
        encoded = size % 256
        entries.extend(struct.pack("<BBBBHHII", encoded, encoded, 0, 0, 1, 32, len(image), offset))
        payload.extend(image)
        offset += len(image)
    return struct.pack("<HHH", 0, 1, len(images)) + entries + payload


def build_ico(source=None):
    shapes = scene(source if source is not None else (ROOT / SOURCE).read_bytes())
    return ico([(size, png(size, shapes)) for size in SIZES])


def generated_assets(root=ROOT):
    source = (root / SOURCE).read_bytes()
    shapes = scene(source)
    images = [(size, png(size, shapes)) for size in SIZES]
    icon = ico(images)
    assets = {
        "assets/windows/provelume.ico": icon,
        "core/provelume/static/brand/provelume.ico": icon,
        "core/provelume/static/brand/provelume.svg": source,
    }
    assets.update(
        {f"core/provelume/static/brand/provelume-{size}.png": image for size, image in images}
    )
    manifest = {
        "schema_version": 2,
        "product": "Provelume",
        "source": SOURCE,
        "source_sha256": hashlib.sha256(source).hexdigest(),
        "generator": "scripts/generate_windows_icon.py",
        "output": "assets/windows/provelume.ico",
        "sizes": list(SIZES),
        "external_resources": False,
        "accessible_text_replacement": False,
        "fallback_order": ["versioned_asset", "executable_resource", "controlled_system_icon"],
        "rendering": {"supersample": SUPERSAMPLE, "cubic_segments": 32, "png_deflate": "stored"},
        "outputs": {
            path: {"sha256": hashlib.sha256(content).hexdigest(), "bytes": len(content)}
            for path, content in sorted(assets.items())
        },
    }
    payload = (json.dumps(manifest, indent=2) + "\n").encode()
    assets["assets/windows/icon-manifest.json"] = payload
    assets["core/provelume/static/brand/icon-manifest.json"] = payload
    return assets


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--output", type=Path, help="Compatibility mode: generate/check only this ICO"
    )
    args = parser.parse_args()
    try:
        assets = (
            {args.output: build_ico()}
            if args.output
            else {ROOT / name: content for name, content in generated_assets().items()}
        )
        for path, content in assets.items():
            if args.check:
                if not path.is_file() or path.read_bytes() != content:
                    print(f"Brand asset missing or stale: {path.name}")
                    return 1
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    except (ValueError, KeyError, ET.ParseError, OSError) as error:
        print(f"Brand generation failed: {error}")
        return 1
    print(f"Provelume brand assets={len(assets)} sizes={list(SIZES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
